### ISSUE TITLE
Deployment Documentation

### ISSUE THREAD

**Issue by tmfdouglas** [Microsoft/TailwindTraders-Backend#1]
As someone with very little experience of Azure, the deployment documentation is impossible to follow.  

As this is meant to be a reference app, could you provide additional detail?

Thanks

**Comment by eiximenis** [comment]
Hi @tmfdouglas 

I updated the deploy doc (https://github.com/Microsoft/TailwindTraders-Backend/blob/master/Documents/DeploymentGuide.md)

Take a look to see if it solves your issues, and if not, please **feel free the reopen the issue** and put a comment where you are having problems.
