### ISSUE TITLE
Step(s) to populate data missing

### ISSUE THREAD

**Issue by ericvanwijk** [microsoft/TailwindTraders-Backend#10]
The deployment guide does not contain steps to populate data. The most visible result is broken images, as the storage account that should contain them is empty.

Can this be included?

**Comment by isaac2004** [comment]
Not having the Azure storage accounts populated with a data is a big miss, At least include a storage account there so we can manually update

**Comment by eiximenis** [comment]
Hi!
I've updated the doc and added a script (`/Deploy/Deploy-Pictures-Azure.ps1`) that copies images to Azure Storage.
There is also the option to run an azure storage emulator in AKS.
