### ISSUE TITLE
Add Pre-Req step to create or reuse existing Service Principal

### ISSUE THREAD

**Issue by ghoelzer-rht** [microsoft/TailwindTraders-Backend#15]
To help expedite the deployment of the the Azure ARM Template, put a Pre-Req step in the Doco to create or reuse an existing Service Principal.  Otherwise, you get to the portal, and then have to go back and find or create one.

Stuff like this may seem trivial, but really interrupts the flow of Workshops, etc., especially the 1st time through.

**Comment by eiximenis** [comment]
Hi @ghoelzer-rht 
Thanks for the suggestion! We will update the doc!

Just commenting: There is now a Powershell script (`/Deploy/Deploy-Arm-Azure.ps1`) that deploys the ARM script creating the service principal by you.

**Comment by ivilches** [comment]
I've proposed a few lines in the docs -> #38 , Documents/DeploymentGuide.md and Documents/Azure-Deployment.md files.

**Comment by olgamarti** [comment]
Solved in commit c5b93d4
