### ISSUE TITLE
Add another Pre-Req to validate ability to deploy SQL Server to target region

### ISSUE THREAD

**Issue by ghoelzer-rht** [microsoft/TailwindTraders-Backend#16]
From time to time MS Internal Subscriptions are restricted from provisioning Azure resources such as SQL Server in a given region (such as Central US today) due to capacity constraints.

**Comment by ivilches** [comment]
I humbly think it's not such a recurrent problem...

**Comment by olgamarti** [comment]
We removed SQL Server from the architecture of the application, and now we are only using CosmoDB.
