### ISSUE TITLE
Tailwind.Traders.Coupon.Api won't compile

### ISSUE THREAD

**Issue by vRITHNER** [Microsoft/TailwindTraders-Backend#2]
when I can't to deploy the ASK services, the Tailwind.Traders.Coupon.Api won't compile:

`C:\Program Files\dotnet\sdk\2.2.100\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.ConflictResolution.targets(33,5): error NETSDK1052: Framework list file path 'v4.0.30319\RedistList\FrameworkList.xml' is not rooted. Only full paths are supported. [D:\!Training\TailwindTraders\TailwindTraders-Backend\Source\Services\Tailwind.Traders.Coupon.Api\Tailwind.Traders.Coupon.Api.njsproj]`

**Comment by dasanagu** [comment]
Hi @vRITHNER this is issue is now fixed with commit [c79ecb](https://github.com/Microsoft/TailwindTraders-Backend/commit/c79ecb98528810f8f22a15d5649c15b491a884b1)
