### ISSUE TITLE
Template Validation Fails - Deployment Fails

### ISSUE THREAD

**Issue by gbuckmaster** [microsoft/TailwindTraders-Backend#25]
Attempting to deploy to Azure results in an invalid template error which blows up the deployment:

The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is 'a9adae50-b041-46a4-a8ae-26c4fa342c8b'.

I'm a Microsoft employee and happy to work with you on the issue to resolve it.

**Comment by eiximenis** [comment]
Hi @gbuckmaster 
Could be the value of `aksVersion` parameter? It's defaulted to `1.12.5` and maybe this value is not correct in the location you tried the deployment...
Just to check, there is a way now to deploy de ARM using powershell. The powershell script ensures the value passed to `aksVersion` parameter is correct

Script is  `/Deploy/Deploy-Arm-Azure.ps1`

**Comment by olgamarti** [comment]
Thanks for try the demo. Please, if you are still experiencing this problem, re-open the issue.
