### ISSUE TITLE
Task "Azure Resource Group Deployment" fails "The value of parameter orchestratorProfile.OrchestratorVersion is invalid."

### ISSUE THREAD

**Issue by thoaingan** [microsoft/TailwindTraders-Backend#26]
Starting: Azure Deployment:Create Or Update Resource Group action on TailwindTradersBackend
==============================================================================
Task         : Azure Resource Group Deployment
Description  : Deploy an Azure resource manager (ARM) template to a resource group. You can also start, stop, delete, deallocate all Virtual Machines (VM) in a resource group
Version      : 2.147.4
Author       : Microsoft Corporation
Help         : [More Information](https://aka.ms/argtaskreadme)
==============================================================================
Checking if the following resource group exists: TailwindTradersBackend.
Resource group exists: false.
Creating resource Group: TailwindTradersBackend
Resource Group created successfully.
Creating deployment parameters.
The detected encoding for file '/home/vsts/work/1/s/Deploy/deployment.json' is 'utf-8'
Starting Deployment.
Deployment name is deployment-20190510-170852-fcf6
There were errors in your deployment. Error code: InvalidTemplateDeployment.
##[error]The template deployment 'deployment-20190510-170852-fcf6' is not valid according to the validation procedure. The tracking id is '81cb7516-5649-4b05-a49f-0ea2c3399aff'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
##[error]Details:
##[error]InvalidParameter: Provisioning of resource(s) for container service tailwindtradersaksdpdfqfju5ljee in resource group TailwindTradersBackend failed. Message: {
  "code": "InvalidParameter",
  "message": "The value of parameter orchestratorProfile.OrchestratorVersion is invalid.",
  "target": "orchestratorProfile.OrchestratorVersion"
 }. Details:  undefined
##[error]Task failed while creating or updating the template deployment.
Finishing: Azure Deployment:Create Or Update Resource Group action on TailwindTradersBackend

**Comment by eiximenis** [comment]
Hi,
You need to pass a valid value to `aksVersion`. The default value may not be correct depending the location.

Starting now it is possible to use powershell to deploy the ARM script, by running `/Deploy/Deploy-Arm-Azure.ps1`. This powershell ensures the value of `aksVersion` is correct given the location where the deployment is triggered.
