### ISSUE TITLE
Create-Secret.ps1 - set explicit az output to json

### ISSUE THREAD

**Issue by buzzfrog** [microsoft/TailwindTraders-Backend#27]
If you have a different output format than json, this command will fail.
`$(az acr show -n $acrName -g $resourceGroup | ConvertFrom-Json).loginServer`

add -o json.

It is the same problem on the next line also.

**Comment by eiximenis** [comment]
Thanks for the suggestion.
We really need to do it!

**Comment by ivilches** [comment]
Fixed in #38 
Thank you @buzzfrog!

**Comment by olgamarti** [comment]
Solved in commit c5b93d4
