### ISSUE TITLE
Looks the project can't be compiled from Visual Studio 

### ISSUE THREAD

**Issue by vRITHNER** [Microsoft/TailwindTraders-Backend#3]
Hi,

When I try to compile from VS 2019 preview, I get an error: 

> Error		**Value cannot be null**.
> Parameter name: stream	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	291	

Looks like it happened exactly like the following error from SmartHotel360 still opened:
[(https://github.com/Microsoft/SmartHotel360/issues/1](https://github.com/Microsoft/SmartHotel360/issues/1)

if I try to build using CLI` dotnet build Tailwind.Traders.Backend.sln`
I get the following error:

> C:\Program Files\dotnet\sdk\2.2.100\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.ConflictResolution.targets(33,5): error NETSDK1052: Framework list file path 'v4.0.30319\RedistList\FrameworkList.xml' is not rooted. Only full paths are supported. [D:\!Training\TailwindTraders\TailwindTraders-Backend\Source\Services\Tailwind.Traders.Coupon.Api\Tailwind.Traders.Coupon.Api.njsproj]

docker-compose build issues:

the docker file contains the following statement:
[RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
    && rm -rf /var/lib/apt/lists/*](url)

which breaks on windows; looking in forums and found I should modify the command :

[RUN apt-get update \
    -and apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
    -and rm -rf /var/lib/apt/lists/*](url)

Now, I get the following error:

> apt-get : The term 'apt-get' is not recognized as the name of a cmdlet,
> function, script file, or operable program. Check the spelling of the name, or
> if a path was included, verify that the path is correct and try again.
> At line:1 char:76
> + ... e = 'Stop'; $ProgressPreference = 'SilentlyContinue'; apt-get update  ...
> +                                                           ~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (apt-get:String) [], ParentConta
>    insErrorRecordException
>     + FullyQualifiedErrorId : CommandNotFoundException

If I command this statement, the next step report the following error:

> Successfully built 91e1c97860e9
> Successfully tagged tailwindtraders/mobileapigw:latest
> Building stock.api
> Step 1/16 : FROM openjdk:8-jre AS base
>  ---> dd20fb277e3c
> Step 2/16 : WORKDIR /app
>  ---> Using cache
>  ---> ba30ea0e0279
> 
> Step 3/16 : FROM openjdk:8-jdk AS maven
>  ---> c14ba9d23b3a
> Step 4/16 : WORKDIR /src
>  ---> Using cache
>  ---> 566d132012f2
> Step 5/16 : COPY . .
>  ---> Using cache
>  ---> 960a75e16576
> Step 6/16 : RUN chmod +x ./mvnw
>  ---> Using cache
>  ---> 076febd195d1
> Step 7/16 : RUN ./mvnw install
>  ---> Running in ad4456225d23
> /bin/sh: 1: ./mvnw: not found
> ERROR: Service 'stock.api' failed to build: The command '/bin/sh -c ./mvnw install' returned a non-zero code: 127
> 

txs

**Comment by eiximenis** [comment]
Hi!
Could you try if removing the nsproj from the sln solves the issue?

**Comment by eiximenis** [comment]
Hi again!
I removed the nsproj from the solution and it worked both with Visual Studio 2019 and with dotnet CLI.

**Note**: I updated the csproj because the emulator of cosmosdb do not exists on Linux, and current Dockerfiles only work on Linux containers.
