### ISSUE TITLE
Error while deploying APIs to dev space

### ISSUE THREAD

**Issue by hgaruda** [microsoft/TailwindTraders-Backend#42]
While trying to deploy all the APIs of backend and web to dev space, the process starts but hangs at " Waiting for container image build". The process terminates after about an hour and shows the below message -

Waiting for container image build...Streaming build container logs for service 'tt-coupons' failed with: Server timeout (30000.00ms) elapsed without receiving a message from the server. 4m 57s
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at 'C:\Users\abc\AppData\Local\Temp\Azure Dev Spaces'.
Please include the following Request ID when contacting support: 3d5b48b9-0e19-4f22-b000-07c43df8f7e8
![tt-azds1](https://user-images.githubusercontent.com/46992592/60076015-283a7200-9744-11e9-9458-77f282017b1a.png)

Thanks,
Hoysala

**Comment by eiximenis** [comment]
Hi,
This is probably because you have not deployed de `ttsa` service account on the namespace (`dev` in your screenshot):

**Before** the `azds up` type:

```
kubectl apply -f helm\ttsa.yaml -n dev`
```

This need to be done only once.

**Comment by hgaruda** [comment]
The command helped move past the error.. 

The instruction in the paragraph - "All deployments of Tailwind Traders run under Kubernetes ttsa service account. You need to create manually this service account in the dev namespace. Just type kubectl apply -f ttsa.yaml. Please note that the ttsa.yaml file is in the /Deploy/helm folder, so run this from that folder or use a relative path.' has missed out  **"-n dev"** at the end.

Thank you!
