### ISSUE TITLE
Hard-coded authentication values

### ISSUE THREAD

**Issue by robconery** [microsoft/TailwindTraders-Backend#6]
I do understand this was created for demo purposes so the code below makes sense. If we're to turn it out as a reference application, the hard-coded auth values should be removed.

https://github.com/Microsoft/TailwindTraders-Backend/blob/8ed810773d937989a027f3ec1ba64f2d0ac092ec/Source/Services/Tailwind.Traders.Product.Api/Security/BasicAuthenticationHandler.cs#L52

**Comment by dasanagu** [comment]
Thanks @robconery. On January we will be updating the fake auth method for B2C. Assigning @eiximenis to this issue.
