### ISSUE TITLE
Missing product images

### ISSUE THREAD

**Issue by revodavid** [microsoft/TailwindTraders-Backend#67]
A number of product images seem to be missing, for example Source/Services/Tailwind.Traders.Product.Api/Setup/product-images/product-details/8704649.jpg

This results in results pages like this (using Shop by Photo): 
![image](https://user-images.githubusercontent.com/152948/65557314-bfe86180-dee7-11e9-9881-a159d6a610cb.png)

**Comment by cdemiguel** [comment]
Hello,
Checking this issue i see that 8704649.jpg appears in the actual scaffolding, inside Deploy/tt-images,
But... it is true, inside Products API these images do not appear, 
How are you pushing these images to storage?, we recommmend to use the following script to do this -> PowerShell script: .\Deploy-Pictures-Azure.ps1 inside deploy folder,

Meanwhile we are going to fix this and put the same images into the 2 folders in future iterations,
I hope to hear from you,
thanks,
Regards

**Comment by olgamarti** [comment]
Thanks for try the demo. Please, if you are still experiencing this problem, re-open the issue.
