### ISSUE TITLE
Deploy to Azure button fails

### ISSUE THREAD

**Issue by spboyer** [microsoft/TailwindTraders-Backend#71]
**Microsoft.ContainerService/managedClusters - Conflict**

```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"CreateRoleAssignmentError\",\r\n \"message\": \"We are unable to serve this request due to an internal error, Correlation ID: 00000000-0000-0000-0000-000000000000, Operation ID: ba9c7d39-6393-47ea-b8ab-d88ead36b79b, Timestamp: 2019-10-04T15:12:21Z.\"\r\n }\r\n ]\r\n }\r\n}"}]}
```

**Comment by scautomation** [comment]
deploy to azure button fails but says its succeeded, not deploying any resources in my subscription.

**Comment by isaacrlevin** [comment]
Hey @spboyer are you still seeing this? Are you able to test on a subscription that does not have an existing cluster?

**Comment by olgamarti** [comment]
Hi @spboyer , we made some changes to the repo since you opened the issue. We tested the deployment button this week, and it succeeds in the deployment. Please, can you try again and re-open the problem if you still have problems? We will be pleased to help.
