### ISSUE TITLE
Generate-Config.ps1: Command 'az cosmosdb list-keys' has been deprecated

### ISSUE THREAD

**Issue by petertuton** [microsoft/TailwindTraders-Backend#79]
Deploy/powershell/Generate-Config.ps1 uses `az cosmosdb list-keys` which has been deprecated. Replace with `az cosmosdb keys list`. 

Running the script as is outputs the following warning (twice, as it's currently called twice):
```
This command has been deprecated and will be removed in a future release. Use 'cosmosdb keys list' instead.
```

**Comment by olgamarti** [comment]
This issue is fixed in #84 . Please, if you are still experiencing this problem, re-open the issue. Thanks!
