### ISSUE TITLE
Error from server (NotFound): deployments.extensions "tiller-deploy" not found

### ISSUE THREAD

**Issue by ericvanwijk** [Microsoft/TailwindTraders-Backend#8]
The statement in add-tiller.sh:

`kubectl patch deploy --namespace kube-system tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'   `

 fails:

> Error from server (NotFound): deployments.extensions "tiller-deploy" not found

Is a pre-requisite missing?

**Comment by ericvanwijk** [comment]
It appears the patched configuration is in place after:
`helm init --service-account tiller`
So I think the error can be ignored (and the patch statement removed?)

**Comment by eiximenis** [comment]
Hi @ericvanwijk 
You're true, error can be ignored and patch statement removed.

I'll update the script. Thanks for reporting!

**Comment by isaac2004** [comment]
@eiximenis @dasanagu Script is still not updated FYI
