### ISSUE TITLE
Deploy-Images-Aks.ps1: Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by petertuton** [microsoft/TailwindTraders-Backend#82]
Deploy-Images-Aks.ps1: `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"`

As per https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-27T21:11:27Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

Fix: Update each of the template deployment.yaml files to `apiVersion: apps/v1`

**Comment by olgamarti** [comment]
Hi Peter, for this demo we are using 1.15, because 1.16 is still in preview. We will review in detail the APIs deprecation once we upgrade to K8s 1.16.
Besides, we updated the apiVersion on PR #84, it's working on 1.14 and 1.15 for us.
