### ISSUE TITLE
Not clear where the images are?

### ISSUE THREAD

**Issue by rbitia** [Microsoft/TailwindTraders-Backend#9]
I think this documentation can improved specifically to manually tag and push images -> where are the dockerfiles, or the image names? 

Taken from the AKS documentation for how to deploy this demo with helm:
Run docker-compose build and then manually tag and push the images to your ACR.

Note: Under WSL docker daemon do not run, so you won't be able to use docker-compose build unless you configure docker client to use the Docker CE for Windows daemon. You can always build docker images using Docker CE for Windows, from a Windows command prompt, and run all scripts from WSL.

**Comment by eiximenis** [comment]
Hi @rbitia 
I updated the doc and added a new PS1 script to make easy the build and push process.

Let me know if this solves the issue and close it if everything is OK. If not, please drop me a comment.

/cc @dasanagu
